GCC_PREFIX=
CFLAGS=-O3 -march=armv7-a -mtune=cortex-a8 -pipe

all:ClCamIp
	@echo "[By MrAs2an]"

ClCamIp: ClCamIp.c
	$(GCC_PREFIX)-gcc $(CFLAGS) -o ClCamIp.out ClCamIp.c 

clean: 
	rm -f  ClCamIp.out 
